baseURL = "https://blog.isayme.org/"
languageCode = "en-us"
title = "BLOG - ISAYME"
theme = "harbor"
summaryLength = 1

[params]
customCSS = ["/css/custom.css"] # in case you use `/static/css/custom.css`
