baseURL = "https://briteming.github.io/ismb/"
languageCode = "en-us"
title = "BLOG OF BRITE"
theme = "harbor"
summaryLength = 1

[params]
customCSS = ["/css/custom.css"] # in case you use `/static/css/custom.css`
