name: ISSUE

on:
  issues:
    types: [opened, edited, deleted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Install Deps
        run: npm install @actions/github

      - name: Update Issue
        if: github.event.action == 'opened' || github.event.action == 'edited'
        run: |
          node ./script/update-issue.js
          git add ./content
          git commit -m "update content/posts/${{ github.event.issue.id }}.md"
          git push
